# Site settings
title: Jimmylin Blog
SEOTitle: 瘸子林的博客 | Jimmylin Blog
header-img: img/laptop-mobile-phone-and-water-glass-on-wooden-table.jpg
email: binglin1219@163.com
description: "Talk is cheap, Show me the code."
keyword: "Jimmylin, Jimmylin Blog, 瘸子林的博客, 林丙, linbing, java, python, devops"
url: "http://linbing1219.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/linbing1219/linbing1219.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Talk is cheap, Show me the code."
sidebar-avatar: /img/about_me.jpeg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     linbing1219
github_username:    linbing1219
facebook_username:
jianshu_username:
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: linbing

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: a9c23aa7c90372593346                            #生成的clientID
  clientSecret: ea756e8a167cb0507b2444f63b4c470b36232bf2    #生成的clientSecret
  repo: linbing1219.github.io    #仓库名称
  owner: linbing1219    #github用户名
  admin: linbing1219
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "hadoop",
        href: "https://github.com/apache/hadoop"
    },{
        title: "spring",
        href: "https://github.com/spring/spring"
    }
]
